apiVersion: 1
datasources:
  - name: Athena
    type: grafana-athena-datasource
    access: proxy
    isDefault: true
    jsonData:
      defaultRegion: cn-northwest-1
      catalog: AwsDataCatalog
      database: algo_metrics
      workgroup: primary
      outputLocation: s3://algo-athena-results/
    editable: true
